# Auditd Config Testing

name: Auditd Syntax Checks

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install auditd
        run: sudo apt-get install -y auditd

      - name: Copy the new rules to the right location
        run: |
          sudo auditctl -D
          sudo cp $GITHUB_WORKSPACE/audit.rules /etc/audit/audit.rules
          
      - name: Check the rules for errors
        run: |          
          sudo augenrules --load # check for errors
          sudo auditctl -l # check for all rules
